# Generated by Django 3.0.1 on 2020-01-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200108_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_you',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
